// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Login with email and password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.AuthEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Revoke refresh token and clear cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "parameters": [
                    {
                        "description": "Refresh payload",
                        "name": "payload",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/me": {
            "get": {
                "description": "Return current authenticated user profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.UserEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/password/forgot": {
            "post": {
                "description": "Request reset password flow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Request password reset token",
                "parameters": [
                    {
                        "description": "Email payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.EmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.OneTimeTokenEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/password/reset": {
            "post": {
                "description": "Reset password using one-time token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Reset password",
                "parameters": [
                    {
                        "description": "Reset password payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Refresh access token using refresh token (cookie or request body).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh payload",
                        "name": "payload",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.TokenEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Register a new user account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "Register payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.RegisterEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/verify-email/confirm": {
            "post": {
                "description": "Verify email using one-time token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Confirm email verification",
                "parameters": [
                    {
                        "description": "Verify email payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.VerifyEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/verify-email/request": {
            "post": {
                "description": "Request email verification flow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Request email verification token",
                "parameters": [
                    {
                        "description": "Email payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.EmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.OneTimeTokenEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard": {
            "get": {
                "description": "Return recipes, meal plans, shopping items and summary in one payload.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get dashboard overview",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/meal-plans": {
            "get": {
                "description": "Return meal plans list used by dashboard/meal-plan page.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meal Plans"
                ],
                "summary": "List meal plans",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max items per page (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.MealPlansEnvelope"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a meal plan menu item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meal Plans"
                ],
                "summary": "Create meal plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Meal plan payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.UpsertMealPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.MealPlanEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/meal-plans/{id}": {
            "put": {
                "description": "Update a meal plan menu item by ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meal Plans"
                ],
                "summary": "Update meal plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Meal Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Meal plan payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.UpsertMealPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.MealPlanEnvelope"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a meal plan menu item by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Meal Plans"
                ],
                "summary": "Delete meal plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Meal Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recipes": {
            "get": {
                "description": "Return recipes list used by dashboard/recipes page.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recipes"
                ],
                "summary": "List recipe cards",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max items per page (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.RecipesEnvelope"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a recipe menu item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recipes"
                ],
                "summary": "Create recipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Recipe payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.UpsertRecipeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.RecipeEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/recipes/{id}": {
            "put": {
                "description": "Update a recipe menu item by ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recipes"
                ],
                "summary": "Update recipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Recipe ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Recipe payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.UpsertRecipeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.RecipeEnvelope"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a recipe menu item by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recipes"
                ],
                "summary": "Delete recipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Recipe ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/shopping-items": {
            "get": {
                "description": "Return shopping items list used by dashboard/shopping page.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shopping Items"
                ],
                "summary": "List shopping items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max items per page (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.ShoppingItemsEnvelope"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a shopping item menu entry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shopping Items"
                ],
                "summary": "Create shopping item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Shopping item payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.UpsertShoppingItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.ShoppingItemEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/shopping-items/{id}": {
            "put": {
                "description": "Update a shopping item menu entry by ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shopping Items"
                ],
                "summary": "Update shopping item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Shopping Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Shopping item payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.UpsertShoppingItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.ShoppingItemEnvelope"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a shopping item menu entry by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shopping Items"
                ],
                "summary": "Delete shopping item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token. Format: Bearer <access_token>",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Shopping Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipebox-backend-go_internal_dto.MessageResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "recipebox-backend-go_internal_dto.AuthEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_dto.AuthResponse"
                }
            }
        },
        "recipebox-backend-go_internal_dto.AuthResponse": {
            "type": "object",
            "properties": {
                "tokens": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_dto.TokenPair"
                },
                "user": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_models.User"
                }
            }
        },
        "recipebox-backend-go_internal_dto.DashboardEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardResponse"
                }
            }
        },
        "recipebox-backend-go_internal_dto.DashboardMealPlan": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mealName": {
                    "type": "string"
                },
                "servings": {
                    "type": "integer"
                }
            }
        },
        "recipebox-backend-go_internal_dto.DashboardRecipe": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "prepTime": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.DashboardResponse": {
            "type": "object",
            "properties": {
                "mealPlans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardMealPlan"
                    }
                },
                "recipes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardRecipe"
                    }
                },
                "shoppingItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardShoppingItem"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardSummary"
                }
            }
        },
        "recipebox-backend-go_internal_dto.DashboardShoppingItem": {
            "type": "object",
            "properties": {
                "checked": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "menuName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qty": {
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.DashboardSummary": {
            "type": "object",
            "properties": {
                "pendingShoppingItemCount": {
                    "type": "integer"
                },
                "recipeCount": {
                    "type": "integer"
                },
                "upcomingMealPlanCount": {
                    "type": "integer"
                }
            }
        },
        "recipebox-backend-go_internal_dto.EmailRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "example": "alkahfii2018@gmail.com",
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "example": "alkahfii2018@gmail.com",
                    "type": "string"
                },
                "password": {
                    "example": "secret123",
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.MealPlanEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardMealPlan"
                }
            }
        },
        "recipebox-backend-go_internal_dto.MealPlansEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardMealPlan"
                    }
                }
            }
        },
        "recipebox-backend-go_internal_dto.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.OneTimeTokenEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_dto.OneTimeTokenResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.OneTimeTokenResponse": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.RecipeEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardRecipe"
                }
            }
        },
        "recipebox-backend-go_internal_dto.RecipesEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardRecipe"
                    }
                }
            }
        },
        "recipebox-backend-go_internal_dto.RefreshRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "example": "refresh-token-sample",
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.RegisterEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_dto.RegisterResponse"
                }
            }
        },
        "recipebox-backend-go_internal_dto.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "example": "alkahfii2018@gmail.com",
                    "type": "string"
                },
                "name": {
                    "example": "Kahfi Smith",
                    "type": "string"
                },
                "password": {
                    "example": "secret123",
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.RegisterResponse": {
            "type": "object",
            "properties": {
                "emailVerification": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_dto.OneTimeTokenResponse"
                },
                "user": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_models.User"
                }
            }
        },
        "recipebox-backend-go_internal_dto.ResetPasswordRequest": {
            "type": "object",
            "properties": {
                "newPassword": {
                    "example": "newSecret123",
                    "type": "string"
                },
                "token": {
                    "example": "reset-token-sample",
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.ShoppingItemEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardShoppingItem"
                }
            }
        },
        "recipebox-backend-go_internal_dto.ShoppingItemsEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipebox-backend-go_internal_dto.DashboardShoppingItem"
                    }
                }
            }
        },
        "recipebox-backend-go_internal_dto.TokenEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_dto.TokenPair"
                }
            }
        },
        "recipebox-backend-go_internal_dto.TokenPair": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "accessTokenExpiresAt": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "refreshTokenExpiresAt": {
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.UpsertMealPlanRequest": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mealName": {
                    "type": "string"
                },
                "servings": {
                    "type": "integer"
                }
            }
        },
        "recipebox-backend-go_internal_dto.UpsertRecipeRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "prepTime": {
                    "type": "integer"
                }
            }
        },
        "recipebox-backend-go_internal_dto.UpsertShoppingItemRequest": {
            "type": "object",
            "properties": {
                "checked": {
                    "type": "boolean"
                },
                "menuName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qty": {
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_dto.UserEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/recipebox-backend-go_internal_models.User"
                }
            }
        },
        "recipebox-backend-go_internal_dto.VerifyEmailRequest": {
            "type": "object",
            "properties": {
                "token": {
                    "example": "verify-token-sample",
                    "type": "string"
                }
            }
        },
        "recipebox-backend-go_internal_models.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "emailVerifiedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "RecipeBox Backend API",
	Description:      "API for RecipeBox backend services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
